# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('quiz', '0001_initial'), ('quiz', '0002_auto_20160208_2246'), ('quiz', '0003_auto_20160209_0003'), ('quiz', '0004_answer_question'), ('quiz', '0005_auto_20160209_0510')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.BooleanField()),
                ('correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024)),
                ('answer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=16384)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(through='quiz.QuizQuestion', to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.UserQuiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='empty', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_answer',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')]),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.Question'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='userquiz',
            options={'verbose_name_plural': 'UserQuizzes'},
        ),
        migrations.AddField(
            model_name='userquiz',
            name='num_correct',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
